[build]
  command = "npx prisma generate"
  publish = "public"

[functions]
  node_bundler = "esbuild"
  included_files = ["generated/**", "node_modules/swagger-ui-dist/**"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/index"
  status = 200